0.4.11

diff --git a/bin/is b/bin/is
--- a/bin/is
+++ b/bin/is
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-source "${BASH_SOURCE%/*}/util"
+#source "${BASH_SOURCE%/*}/util"
 
 # @usage: is <kind> <value>
 # Beispiel:
@@ -8,16 +8,15 @@ source "${BASH_SOURCE%/*}/util"
 #   is array myArr         && echo "is an indexed arraz"
 #   is function myFunc     && echo "is a shell function"
 declare -F is >/dev/null || {
-
-    is() {
+    is(){
         local error=()
         if [ $# == 1 ]; then
             case "$1" in
-                online) (echo > /dev/tcp/8.8.8.8/53) 2>/dev/null;;
-                *) error=(2 "missing second argument");;
+                online) timeout 1 bash -c 'echo > /dev/tcp/8.8.8.8/53' 2>/dev/null || error=($? "offline");;
             esac
+        elif [ -z "$2" ]; then
+            error=(2 "missing second argument")
         else
-            [ -z "$2" ] && error=(1 "empty value")
             case "$1" in
                 block) [[ -b "$2" ]] || error=(1 "is not a block-device");;
                 char) [[ -c "$2" ]] || error=(1 "is not a char-device");;
@@ -69,7 +68,7 @@ declare -F is >/dev/null || {
                     ;;
             esac
         fi
-        (( ${#error[@]} )) && echo -e "\e[31mError #${error[0]}: ${error[1]}\e[0m" >&2
+        [ ${#error[@]} == 0 ] || echo -e "\e[31mError #${error[0]}: ${error[1]}\e[0m" >&2
         return "${error[0]:-0}"
     }
 
